### ISSUE TITLE
Add tests for IE helper methods

### ISSUE THREAD

**Issue by wmnsk** [wmnsk/go-pfcp#70]
To ensure each method returns the expected value, we should add unit tests for them.

- [ ] uint8 (`ie_uint8_test.go` / #63, #69)
- [ ] uint16 (`ie_uint16_test.go` / #66)
- [ ] uint32
- [ ] uint64
- [ ] string (`ie_string_test.go` / tests for grouped IE should be added)
- [ ] bool
- [ ] time.Duration (`ie_duration_test.go` / #67)
- [ ] time.Time (`ie_time_test.go` / #68)
- [ ] others

**Comment by wmnsk** [comment]
## uint32

- [ ] AggregatedURRID
- [ ] AveragingWindow
- [ ] CumulativeRateRatioMeasurement
- [ ] CumulativeRateRatioThreshold
- [ ] DSTTPortNumber
- [ ] EthernetFilterID
- [ ] EventQuota
- [ ] EventThreshold
- [ ] FailedRuleID
- [ ] FARID
- [ ] FramedRouting
- [ ] GBRUL
- [ ] GBRDL
- [ ] InactivityDetectionTime
- [ ] LinkedURRID
- [ ] MBRUL
- [ ] MBRDL
- [ ] Exponent
- [ ] NWTTPortNumber
- [ ] Precedence
- [ ] QERCorrelationID
- [ ] QERID
- [ ] QueryURRReference
- [ ] SequenceNumber
- [ ] SubsequentEventQuota
- [ ] SubsequentEventThreshold
- [ ] SubsequentTimeThreshold
- [ ] TimeThreshold
- [ ] URSEQN
- [ ] URRID

## uint64

- [ ] ValueDigits

## bool

- [ ] HasAURI
- [ ] HasDROP
- [ ] HasFORW
- [ ] HasBUFF
- [ ] HasNOCP
- [ ] HasDUPL
- [ ] HasLLI
- [ ] HasLOAD
- [ ] HasOVRL
- [ ] HasBII
- [ ] HasTTC
- [ ] HasSCI
- [ ] HasPPI
- [ ] HasQFI
- [ ] HasDLBY
- [ ] HasDLPA
- [ ] HasBIDE
- [ ] HasETHI
- [ ] HasN3
- [ ] HasN9
- [ ] IsVendorSpecific
- [ ] IsGrouped
- [ ] HasISTM
- [ ] HasRADI
- [ ] HasINAM
- [ ] HasMBQE
- [ ] HasEVENT
- [ ] HasVOLUM
- [ ] HasDURAT
- [ ] HasTCI
- [ ] HasRDSI
- [ ] HasUPFR
- [ ] HasTEID
- [ ] HasIPv4
- [ ] HasIPv6
- [ ] HasCTag
- [ ] HasSTag
- [ ] IsN19
- [ ] IsN6
- [ ] HasDLPR
- [ ] HasULPR
- [ ] HasPRIUEAI
- [ ] HasPRINT19I
- [ ] HasPRIN6I
- [ ] HasDCARONI
- [ ] HasURSS
- [ ] HasSARR
- [ ] HasPSREI
- [ ] HasPARPS
- [ ] HasRESTI
- [ ] HasDROBU
- [ ] HasSNDEM
- [ ] HasQAURR
- [ ] HasPSDBU
- [ ] HasPMFI
- [ ] HasINS
- [ ] HasARP
- [ ] HasNORD
- [ ] HasMODE
- [ ] HasRCSR
- [ ] HasIRE
- [ ] HasTHR
- [ ] HasPER
- [ ] HasNI
- [ ] HasDI
- [ ] HasUPIR
- [ ] HasERIR
- [ ] HasUSAR
- [ ] HasDLDR
- [ ] HasSESRL
- [ ] HasEVETT
- [ ] HasLIUSA
- [ ] HasDROTH
- [ ] HasSTOPT
- [ ] HasSTART
- [ ] HasQUHTI
- [ ] HasTIMTH
- [ ] HasVOLTH
- [ ] HasPERIO
- [ ] HasEVEQU
- [ ] HasEVETH
- [ ] HasMACAR
- [ ] HasENVCL
- [ ] HasTIMQU
- [ ] HasVOLQU
- [ ] HasRRCA
- [ ] HasRRCR
- [ ] HasRRTO
- [ ] HasRP
- [ ] HasUL
- [ ] HasDL
- [ ] HasRQI
- [ ] HasMAC
- [ ] HasCH
- [ ] HasIPv6D
- [ ] HasSD
- [ ] HasBUCP
- [ ] HasDDND
- [ ] HasDLBD
- [ ] HasTRST
- [ ] HasFTUP
- [ ] HasPFDM
- [ ] HasHEEU
- [ ] HasTREU
- [ ] HasEMPU
- [ ] HasPDIU
- [ ] HasUDBC
- [ ] HasQUOAC
- [ ] HasTRACE
- [ ] HasFRRT
- [ ] HasPFDE
- [ ] HasEPFAR
- [ ] HasDPDRA
- [ ] HasADPDP
- [ ] HasUEIP
- [ ] HasSSET
- [ ] HasMNOP
- [ ] HasMTE
- [ ] HasBUNDL
- [ ] HasGCOM
- [ ] HasMPAS
- [ ] HasRTTL
- [ ] HasVTIME
- [ ] IsAllocatedByCPFunction
- [ ] IsAllocatedByUPFunction
- [ ] HasUBE
- [ ] HasUAE
- [ ] HasAFT
- [ ] HasBEF
- [ ] HasIMMER
- [ ] HasMONIT
- [ ] HasTERMR
- [ ] HasASSONI
- [ ] HasASSOSI
